local _LS = require("runtime/core/enhanced_runtime")

-- Generated by LUASCRIPT Enhanced Transpiler
-- Mathematical programming with Unicode operator support

(LUASCRIPT = LUASCRIPT - 1)
Runtime
Library
Integration
local
runtime = require("runtime.runtime")
local
console = runtime.console
local
JSON = runtime.JSON
local
Math = runtime.Math
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil
nil