local _LS = require("runtime/core/enhanced_runtime")

-- Generated by LUASCRIPT Enhanced Transpiler
-- Mathematical programming with Unicode operator support

local mirrorName = "Project Mirror"
local mirrorVersion = "v0"
local mirrorReady = true