local _LS = require("runtime/core/enhanced_runtime")

-- Generated by LUASCRIPT Enhanced Transpiler
-- Mathematical programming with Unicode operator support

function fibonacci(n)
  if (n <= 1) then
    return n
  end
  return (fibonacci((n - 1)) + fibonacci((n - 2)))
end
local fib5 = fibonacci(5)
local parityPass = (fib5 == 5)