local _LS = require("runtime/core/enhanced_runtime")

-- Generated by LUASCRIPT Enhanced Transpiler
-- Mathematical programming with Unicode operator support

function factorial(n)
  local result = 1
  local i = 2
  while (i <= n) do
    result = (result * i)
    i = (i + 1)
  end
  return result
end
local fact5 = factorial(5)
local deterministicPass = (fact5 == 120)