local _LS = require("runtime/core/enhanced_runtime")

-- Generated by LUASCRIPT Enhanced Transpiler
-- Mathematical programming with Unicode operator support

function sumToN(n)
  local sum = 0
  local i = 1
  while (i <= n) do
    sum = (sum + i)
    i = (i + 1)
  end
  return sum
end
local perfSum = sumToN(100)
local perfPass = (perfSum == 5050)