local _LS = require("runtime/core/enhanced_runtime")

-- Generated by LUASCRIPT Enhanced Transpiler
-- Mathematical programming with Unicode operator support

local testCount = 165
local passRate = 100
local metricStr = "tests-passing"
local metricLen = 5