local _LS = require("runtime/core/enhanced_runtime")

-- Generated by LUASCRIPT Enhanced Transpiler
-- Mathematical programming with Unicode operator support

local a = 10
local b = 3
local add = (a + b)
local sub = (a - b)
local mul = (a * b)
local div = (a / b)
local eq = (a == 10)
local ne = (a ~= 5)
local lt = (a < 20)
local le = (a <= 10)
local gt = (a > 5)
local ge = (a >= 10)
local and1 = (true and true)
local and2 = (true and false)
local or1 = (false or true)
local or2 = (false or false)
local resultAdd = (add == 13)
local resultMul = (mul == 30)
local resultEq = ((eq and ne) and lt)