local _LS = require("runtime/core/enhanced_runtime")

-- Generated by LUASCRIPT Enhanced Transpiler
-- Mathematical programming with Unicode operator support

local outer = 100
local inner = (outer + 50)
local x = 0
if true then
  x = (x + 1)
end
local y = x
local funcLocal = 999
local funcResult = funcLocal
local isCorrect = ((funcResult == 999) and (y == 1))