local _LS = require("runtime/core/enhanced_runtime")

-- Generated by LUASCRIPT Enhanced Transpiler
-- Mathematical programming with Unicode operator support

local status = "ok"
local ready = false
if (status == "ok") then
  ready = true
else
  ready = false
end