local _LS = require("runtime/core/enhanced_runtime")

-- Generated by LUASCRIPT Enhanced Transpiler
-- Mathematical programming with Unicode operator support

local sum = 0
local count = 0
while (count < 10) do
  sum = (sum + count)
  count = (count + 1)
end
local whileResult = (sum == 45)
local sum2 = 0
local i = 0
while (i < 5) do
  sum2 = (sum2 + i)
  i = (i + 1)
end
local whileResult2 = (sum2 == 10)
local final = ((count == 10) and (i == 5))