local _LS = require("runtime/core/enhanced_runtime")

-- Generated by LUASCRIPT Enhanced Transpiler
-- Mathematical programming with Unicode operator support

local a = 10
local b = 20
local result = 0
if (a < b) then
  result = (result + 1)
else
  result = (result + 2)
end
if (a > 5) then
  if (b > 15) then
    result = (result + 10)
  end
end
local nested = 11
local cond1 = (a < b)
local cond2 = (b > 15)
local both = (cond1 and cond2)