local _LS = require("runtime/core/enhanced_runtime")

-- Generated by LUASCRIPT Enhanced Transpiler
-- Mathematical programming with Unicode operator support

local a = 10
local b = 20
local c = (a + b)
if (c > 25) then
  c = (c - 5)
else
  c = (c + 5)
end
local irStable = (c == 30)