local _LS = require("runtime/core/enhanced_runtime")

-- Generated by LUASCRIPT Enhanced Transpiler
-- Mathematical programming with Unicode operator support

local smokeTotal = 0
local i = 0
while (i <= 10) do
  smokeTotal = (smokeTotal + i)
  i = (i + 1)
end
local smokeOk = (smokeTotal == 55)