local _LS = require("runtime/core/enhanced_runtime")

-- Generated by LUASCRIPT Enhanced Transpiler
-- Mathematical programming with Unicode operator support

local arr = _LS.array({1, 2, 3, 4, 5})
local result = 0
local idx = 0
while (idx < 5) do
  result = (result + arr[idx])
  idx = (idx + 1)
end
local edgeCasePass = (result == 15)