local _LS = require("runtime/core/enhanced_runtime")

-- Generated by LUASCRIPT Enhanced Transpiler
-- Mathematical programming with Unicode operator support

local str = "hello"
local len = 5
local char0 = "h"
local concat = "hello world"
local test1 = (len == 5)
local test2 = (concat == "hello world")
local idx = 0
local result = ""
while (idx < 5) do
  idx = (idx + 1)
end
local loopTest = (idx == 5)