local _LS = require("runtime/core/enhanced_runtime")

-- Generated by LUASCRIPT Enhanced Transpiler
-- Mathematical programming with Unicode operator support

local arr = _LS.array({1, 2, 3})
for _, item in ipairs(arr) do
  print(item)
end