local _LS = require("runtime/core/enhanced_runtime")

-- Generated by LUASCRIPT Enhanced Transpiler
-- Mathematical programming with Unicode operator support

local name = "World"
local greeting = string.format("Hello, %s!", name)
print(greeting)