local _LS = require("runtime/core/enhanced_runtime")

-- Generated by LUASCRIPT Enhanced Transpiler
-- Mathematical programming with Unicode operator support

local x = _LS.add(2, 3)
local y = (x * 4)
print("sum", x)
print("product", y)