local _LS = require("runtime/core/enhanced_runtime")

-- Generated by LUASCRIPT Enhanced Transpiler
-- Mathematical programming with Unicode operator support

local message = "Hello from LUASCRIPT!"
local version = 1.0
function greet(name)
  return string.format("Hello, %s! Welcome to LUASCRIPT v%s", name, version)
end
function fibonacci(n)
  if (n <= 1) then
    return n
  end
  return (fibonacci((n - 1)) + fibonacci((n - 2)))
end
print(message)
print(greet("World"))
print("Fibonacci(10):", fibonacci(10))
local numbers = _LS.array({1, 2, 3, 4, 5})
local doubled = _LS.map(numbers, function(x) return (x * 2) end)
local sum = _LS.reduce(doubled, function(a, b) return (a + b) end, 0)
print("Original:", numbers)
print("Doubled:", doubled)
print("Sum:", sum)