local _LS = require("runtime/core/enhanced_runtime")

-- Generated by LUASCRIPT Enhanced Transpiler
-- Mathematical programming with Unicode operator support

local message = "Hello from LUASCRIPT!"
local version = 1.0
function greet(name)
  return (("Hello, " .. name) .. "!")
end
function fibonacci(n)
  if (n <= 1) then
    return n
  end
  return (fibonacci((n - 1)) + fibonacci((n - 2)))
end
print(message)
print(greet("World"))
print("Fibonacci(10):", fibonacci(10))